version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ${ES_JAVA_OPTS}
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  opencv:
    build: ./opencv
    env_file: 
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - elasticsearch

  backend:
    build: ./backend
    env_file: 
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "3000:80"

volumes:
  esdata: